version:  '3.5'
services:
  server:
    image: qweasdqwe/message-example:latest
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres_db
    networks:
      - "testing-network"
    depends_on:
      - postgres_db

  postgres_db:
    image:  postgres:12.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - "testing-network"

networks:
  testing-network:
