// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type GetMessagesInput struct {
	StartDate DateTime `json:"startDate"`
	EndDate   DateTime `json:"endDate"`
}

type Message struct {
	ID        string   `json:"id"`
	Text      string   `json:"text"`
	CreatedAt DateTime `json:"createdAt"`
}

type WriteMessageInput struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
